### ISSUE TITLE
Add Jenkins CI for contiki

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [CreatorDev/contiki#10]
Add build step for contiki CI

**Comment by Shpinkso** [comment]
Acceptance:
- Build is automated on PR
- Build is performed in container
- PR initiator is notified of failure

**Comment by Shpinkso** [comment]
We should follow the travis example here: https://github.com/mtusnio/LetMeCreateIoT/blob/master/.travis.yml
i.e. convert this into jenkinsfile equivalent
