### ISSUE TITLE
Evaluate mbedTLS

### ISSUE THREAD

**Issue by Shpinkso** [CreatorDev/contiki#26]
Difficulties with tinyDTLS that are taking a while to solve - this task is to evaluate whether mbedTLS will be the quicker path to secure end-to-end comms over awa.
This task covers the work to switch to mbedTLS on contiki/clicker and see if awa end to end is functional on a secure deviceserver, if not, add tickets to debug/fix

**Comment by mtusnio** [comment]
To build you can setup your Awa application as described in Awalwm2m docs - https://github.com/FlowM2M/AwaLWM2M/blob/master/doc/example_app_static_api.md#example-create-a-standalone-lwm2m-client-within-a-contiki-environment

Put the mbedtls source in Contiki/apps (make sure it's all in a folder called mbedtls). You will probably need to disable some options, navigate to Contiki/apps/mbedtls and run:

``sh
scripts/config.pl unset MBEDTLS_FS_IO
scripts/config.pl unset MBEDTLS_TIMING_C
scripts/config.pl unset MBEDTLS_NET_C
scripts/config.pl set MBEDTLS_NO_PLATFORM_ENTROPY
``

Use the slightly hacky makefile below to build it:

``CONTIKI_PROJECT=static-client-tutorial
CONTIKI=Contiki
LWM2M_DIR=AwaLWM2M
TARGET=mikro-e
PAN_ID=0xaaaa

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\" -DVERSION='\"$(VERSION)\"'
CFLAGS += -Wall -Wno-pointer-sign
CFLAGS += -I$(LWM2M_DIR)/api/include -DLWM2M_CLIENT -g -DDTLS_PEERS_NOHASH=1

CFLAGS += -DUIP_CONF_BUFFER_SIZE=4096

APPS += erbium

APPDIRS += $(LWM2M_DIR)/lib
APPDIRS += $(LWM2M_DIR)/core/src
APPS += client
APPS += common

APPS += mbedtls/include mbedtls/library
APPS += er-coap
APPS += rest-engine
APPS += jsmn
APPS += b64
#APPS += hmac
APPS += libobjects

CONTIKI_WITH_IPV6 = 1
CONTIKI_WITH_RPL = 0
USE_CA8210 = 1
RESOLV_CONF_SUPPORTS_MDNS = 0
UIP_CONF_TCP = 1
MBEDTLS = 1

CFLAGS += -I $(CONTIKI)/platform/$(TARGET)
CFLAGS += -fno-short-double
LDFLAGS += -Wl,--defsym,_min_heap_size=64000

SMALL=0

mbedtls/library_src = aes.c cmac.c error.c padlock.c sha256.c x509.c aesni.c gcm.c pem.c sha512.c  \
              x509_create.c arc4.c ctr_drbg.c havege.c pk.c ssl_cache.c x509_crl.c asn1parse.c \
              debug.c hmac_drbg.c pkcs11.c ssl_ciphersuites.c x509_crt.c asn1write.c des.c \
              pkcs12.c ssl_cli.c x509_csr.c base64.c dhm.c md2.c pkcs5.c ssl_cookie.c \
              x509write_crt.c bignum.c ecdh.c md4.c pkparse.c ssl_srv.c x509write_csr.c \
              blowfish.c ecdsa.c md5.c pk_wrap.c ssl_ticket.c xtea.c camellia.c ecjpake.c md.c \
              pkwrite.c ssl_tls.c ccm.c ecp.c md_wrap.c platform.c threading.c certs.c ecp_curves.c \
              memory_buffer_alloc.c ripemd160.c timing.c cipher.c entropy.c net_sockets.c rsa.c version.c \
              cipher_wrap.c entropy_poll.c oid.c sha1.c version_features.c

all: static-client-tutorial
	xc32-bin2hex static-client-tutorial.$(TARGET)
include $(CONTIKI)/Makefile.include
``
