### ISSUE TITLE
Clicker solution for testing end to end without security

### ISSUE THREAD

**Issue by Shpinkso** [CreatorDev/contiki#4]
An internal device server will be made available to allow insecure bootstrapping and communications to help with debugging when issues appear.
Matt V and Murat will make the server available, we need to ensure that we have a way for people to use an image that work with it.
Test that this works with the standard CI40 image.
Details for people on how to create or work with the image.

**Comment by mtusnio** [comment]
https://github.com/FlowM2M/AwaLWM2M/blob/master/doc/example_app_static_api.md#example-create-a-standalone-lwm2m-client-within-a-contiki-environment
Using the insecure device server is just a case of following the example and changing the addresses for the device server's address. It's equivalent to connecting to an awa server running on a CI40, so there's no need for any extra changes.
