### ISSUE TITLE
Simplify steps for compiling Awa + Contiki + Tinydtls

### ISSUE THREAD

**Issue by mtusnio** [CreatorDev/contiki#47]
At the moment, apart from Awa patches and docs, there need to be some manual changes to compile Tinydtls with Contiki and Awa. We need some simplified environment that can be easily used as reference, possibly a github repo with all the submodules ready for use and docs.

Acceptance
- LMCIoT can be selected in a build as a Contiki app (library)
- Test app for LMC that checks initialisation passes

**Comment by abhijit-mahajani-imgtec** [comment]
git clone --recursive should give all the necessary changed repos (tinydtls with patches, etc in own creatordev repos)

**Comment by mtusnio** [comment]
Blocked on #70
