### ISSUE TITLE
Drop TI clicker support

### ISSUE THREAD

**Issue by francois-berder-imgtec** [CreatorDev/contiki#49]
* Need to tag the lastest commit in 3.0-mikroe and creator branches which works with TI 6LoWPAN clicker
* Remove any reference to TI clicker specific code

**Comment by Shpinkso** [comment]
@francois-berder-imgtec make sure the repo is tagged before dropping support - we need to have a legacy version that people can still use with TI support

**Comment by mtusnio** [comment]
Created two tags: 3.0-mikro-e-cc2520 & creator-cc2520
