### ISSUE TITLE
Add release functions to UART & I2C.

### ISSUE THREAD

**Issue by mtusnio** [CreatorDev/contiki#8]
Right now there's no way to deinit or release the I2C interface after initing, some function to do that would be useful.

**Comment by francois-berder-imgtec** [comment]
No need for that function because it would be very similar to i2c_init except that it would not set SMEN bit.

**Comment by Shpinkso** [comment]
@mtusnio is this still an open issue in your opinion?

**Comment by mtusnio** [comment]
Yes, it's not a high priority, the function should be simple enough (one bit switch), but it'd make sense to keep a release even if we just want to make it future proof in case something more does need to go into there.

**Comment by francois-berder-imgtec** [comment]
The i2c_release function needs to:
*  disable the i2c module
* unregister i2c from lpm module
* power down i2c

Blocked until CreatorDev/contiki#29 is done.
